---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    ui_color.good=purple
    ui_color.bad=yellow
    allow.textmode=true
immutable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-configmap
  labels:
    name: redis-configmap
spec:
  containers:
    - name: mypod
      image: redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/etc/foo"
          name: foo
          readOnly: true
  volumes:
    - name: foo
      configMap:
        name: myconfigmap
